# Generated by Django 5.1.3 on 2025-01-19 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0006_rename_product_producttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
