# Generated by Django 5.1.3 on 2025-01-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0007_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='ProductId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
