# Generated by Django 5.1.3 on 2025-01-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0008_producttable_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='QRCodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_qr_codes/'),
        ),
    ]
