# Generated by Django 5.1.3 on 2025-01-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0010_usertable_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleApp.usertable'),
        ),
    ]
