# Generated by Django 5.1.3 on 2025-01-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0011_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
